import {mediaPlugin,setupMedia} from '/media.js';
const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name="editor-token"]').content;
let posts=[],current=null,dirty=false,bodyDirty=false,loading=false,sourceMode=false,siteUrl=null,busy=false;
const editor=new toastui.Editor({el:$('visual'),height:'620px',plugins:[mediaPlugin],initialEditType:'wysiwyg',hideModeSwitch:true,usageStatistics:false,autofocus:false,toolbarItems:[['heading','bold','italic','strike'],['hr','quote'],['ul','ol','task'],['table','link'],['code','codeblock']],events:{change:()=>{if(!loading){bodyDirty=true;markDirty();}}}});
const message=(text,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error);};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Editor-Token':token}});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;}
function markDirty(){renderOutline();dirty=true;message('Unsaved changes');}
function canLeave(){return !dirty||confirm('You have unsaved changes. Discard them?');}
function drawList(){ $('posts').replaceChildren();for(const p of posts){const button=document.createElement('button');button.type='button';button.className='post'+(current?.id===p.id?' active':'');const title=document.createElement('strong');title.textContent=p.title;const meta=document.createElement('span');meta.textContent=(p.published?(p.hasDraft?'Published · Draft changes':'Published'):'Draft')+' · '+p.date;button.append(title,meta);button.onclick=()=>{if(!busy&&canLeave())load(p);};$('posts').append(button);}}
function setMode(source){sourceMode=source;$('source').hidden=!source;$('visual').hidden=source;$('mode').textContent=source?'Use visual editor':'Use source mode';$('mode-note').textContent=source?'Source mode preserves equations, footnotes, and custom MDX components. Standard posts can use the visual editor.':'Write with the toolbar. Save draft keeps changes private; Publish or Update post changes the website.';}
function updateLinks(){ $('website').hidden=!siteUrl;$('website').href=siteUrl||'#';$('read-post').hidden=!(siteUrl&&current?.published);if(siteUrl&&current)$('read-post').href=siteUrl+'/posts/'+current.id.replace(/\.mdx?$/,'')+'/';}
function load(p){loading=true;current=p;const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());$('title').value=p?.title||'';$('date').value=p?.date||today.toISOString().slice(0,10);$('category').value=p?.category||'Thinking';$('type').value=p?.type||'Note';$('description').value=p?.description||'';$('example').checked=p?.example||false;$('tags').value=(p?.tags||[]).join(', ');$('show-toc').checked=p?.showToc!==false;$('heading').textContent=p?'Edit post':'New post';$('save').textContent=p?.published?'Update post':'Publish';const body=p?.body||'';$('source').value=body;const advanced=Boolean(p&&(p.id.endsWith('.mdx')||/\$|\[\^/.test(body)));setMode(advanced);editor.setMarkdown(advanced?'':body,false);dirty=false;bodyDirty=false;loading=false;message(p?(p.hasDraft?'Draft saved. '+(p.published?'The published version is unchanged.':'Not visible on the website.'): 'Published on your local website.'):'Start writing. Save draft whenever you like.');drawList();updateLinks();renderOutline();}
$('form').addEventListener('input',e=>{if(!loading&&!e.target.id.startsWith('reading-')){if(e.target===$('source'))bodyDirty=true;markDirty();}});
$('new').onclick=()=>{if(!busy&&canLeave()){load(null);$('title').focus();}};
$('mode').onclick=()=>{if(sourceMode){if(/\$|\[\^|<|^import /m.test($('source').value)&&!confirm('This post contains advanced formatting. Visual editing may change it. Keep a backup by saving first. Switch anyway?'))return;loading=true;editor.setMarkdown($('source').value,false);loading=false;setMode(false);}else{$('source').value=bodyDirty?editor.getMarkdown():(current?.body||editor.getMarkdown());setMode(true);}};
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;document.getElementById("form").inert=true;$('save').disabled=true;message('Saving…');const body=!bodyDirty&&current?current.body:sourceMode?$('source').value:editor.getMarkdown();const action=e.submitter?.id==='draft'?'draft':current?.published?'update':'publish';const data={action,id:current?.id,revision:current?.revision,title:$('title').value,date:$('date').value,category:$('category').value,type:$('type').value,description:$('description').value,example:$('example').checked,showToc:$('show-toc').checked,tags:$('tags').value.split(',').map(t=>t.trim()).filter(Boolean),body};
try{const saved=await api('/api/save',{method:'POST',body:JSON.stringify(data)});current=saved;dirty=false;bodyDirty=false;posts=posts.filter(p=>p.id!==saved.id).concat(saved).sort((a,b)=>b.date.localeCompare(a.date));drawList();updateLinks();$('heading').textContent='Edit post';$('save').textContent=saved.published?'Update post':'Publish';message(action==='draft'?'Draft saved. '+(saved.published?'The published version is unchanged.':'Not visible on the website.'):action==='update'?'Post updated on your local website.':'Published on your local website.');}catch(error){message(error.message,true);}finally{busy=false;document.getElementById("form").inert=false;$('save').disabled=false;}};
$('stop').onclick=async()=>{if(busy||!canLeave())return;try{await api('/api/stop',{method:'POST',body:'{}'});clearInterval(poll);dirty=false;$('form').hidden=true;$('closed').hidden=false;$('stop').disabled=true;$('new').disabled=true;$('posts').replaceChildren();$('website').hidden=true;}catch(error){message(error.message,true);}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function checkSite(){try{const state=await api('/api/status');siteUrl=state.siteUrl;updateLinks();if(state.siteError&&!dirty)message(state.siteError,true);}catch{}}
setupMedia({editor,getSourceMode:()=>sourceMode,markBodyChanged:()=>{bodyDirty=true;markDirty();},message,token});
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(!busy)$('form').requestSubmit($('draft'));}});
function applyAppearance(data){const stack=data.font==='Inter'?'InterVariable, Arial, sans-serif':data.font==='Segoe UI'?'Segoe UI, Arial, sans-serif':'Arial, Helvetica, sans-serif';document.documentElement.style.setProperty('--reading-font',stack);document.documentElement.style.setProperty('--reading-size',data.size+'px');$('reading-font').value=data.font;$('reading-size').value=String(data.size);}
$('apply-style').onclick=async()=>{try{const data=await api('/api/appearance',{method:'POST',body:JSON.stringify({font:$('reading-font').value,size:Number($('reading-size').value)})});applyAppearance(data);message('Reading style updated.'+(dirty?' You still have unsaved post changes.':''));}catch(e){message(e.message,true);}};
api('/api/appearance').then(applyAppearance).catch(e=>message(e.message,true));
const poll=setInterval(checkSite,2500);
try{posts=await api('/api/posts');load(null);await checkSite();}catch(error){message('Could not open the notebook. '+error.message,true);}



function renderOutline(){
 const markdown=sourceMode?$('source').value:editor.getMarkdown();let fenced=false;const items=[];let offset=0;
 for(const line of markdown.split('\n')){if(/^\s*(```|~~~)/.test(line))fenced=!fenced;const match=!fenced&&/^(#{2,4})\s+(.+)$/.exec(line);if(match)items.push({level:match[1].length,title:match[2].replace(/[*_`]/g,''),offset});offset+=line.length+1;}
 $('editor-outline').replaceChildren();if(!items.length){const li=document.createElement('li');li.textContent='No sections yet. Add a heading to begin.';$('editor-outline').append(li);return;}
 items.forEach((item,index)=>{const li=document.createElement('li');li.style.marginLeft=((item.level-2)*18)+'px';const button=document.createElement('button');button.type='button';button.textContent=item.title;button.onclick=()=>{if(sourceMode){$('source').focus();$('source').setSelectionRange(item.offset,item.offset+item.title.length+item.level+1);}else {const target=$('visual').querySelectorAll('.toastui-editor-ww-container h2,.toastui-editor-ww-container h3,.toastui-editor-ww-container h4')[index];target?.scrollIntoView({block:'center'});}};li.append(button);$('editor-outline').append(li);});
}
function applyHeading(level){if(sourceMode){const input=$('source');const start=input.value.lastIndexOf('\n',input.selectionStart-1)+1;const end=input.value.indexOf('\n',input.selectionStart);const line=input.value.slice(start,end<0?input.value.length:end).replace(/^#{1,6}\s+/,'');input.setRangeText('#'.repeat(level)+' '+(line||'New section'),start,end<0?input.value.length:end,'end');}else {editor.focus();editor.exec('heading',{level});}bodyDirty=true;markDirty();}
$('section-add').onclick=()=>applyHeading(2);$('subsection-add').onclick=()=>applyHeading(3);$('subsubsection-add').onclick=()=>applyHeading(4);renderOutline();

